### ISSUE TITLE
Issues with --enable-benchmarks, nc_perf, unit tests

### ISSUE THREAD

**Issue by WardF** [Unidata/netcdf-c#2627]
While investigating #2626, I discovered a few issues with the performance tests/benchmarks. 

* Benchmark and performance tests can't be enabled under `cmake`.
* `make check` fails to compile when `--enable-benchmarks` is specified w/out using parallel compilation.

**Comment by WardF** [comment]
## Todo

* [ ] Wire in benchmarks option to `CMakeLists.txt`
* [ ] Make performance tests which require `mpi` conditional on parallel compilation.
* [ ] Ensure performance checks pass.
